,COUNT (CASE WHEN c.scrape_status = 'CATEGORIZED' THEN 'CATEGORIZED' ELSE NULL END) AS CATEGORIZED
,COUNT (CASE WHEN c.scrape_status = 'CATEGORIZE_ERROR' THEN 'CATEGORIZE_ERROR' ELSE NULL END) AS
CATEGORIZE_ERROR
,COUNT (CASE WHEN c.scrape_status = 'USER_AUTHORIZATION_NOT_GRANTED' THEN
'USER_AUTHORIZATION_NOT_GRANTED' ELSE NULL END) AS USER_AUTHORIZATION_NOT_GRANTED
,COUNT (CASE WHEN c.scrape_status = 'UNLOCK_DEVICE' THEN 'UNLOCK_DEVICE' ELSE NULL END) AS
UNLOCK_DEVICE
,COUNT (CASE WHEN c.scrape_status = 'SELECT_OWNERSHIP' THEN 'SELECT_OWNERSHIP' ELSE NULL END) AS
SELECT_OWNERSHIP
,COUNT (CASE WHEN c.scrape_status = 'MFA_EXPIRED' THEN 'MFA_EXPIRED' ELSE NULL END) AS MFA_EXPIRED
,COUNT (CASE WHEN c.scrape_status = 'TRANSLATE_ERROR' THEN 'TRANSLATE_ERROR' ELSE NULL END) AS
TRANSLATE_ERROR
,COUNT(CASE WHEN c.scrape_status = 'SITE_NOT_AVAILABLE' THEN 'SITE_NOT_AVAILABLE' ELSE NULL END) AS
SITE_NOT_AVAILABLE
,COUNT (CASE WHEN c.scrape_status = 'MFA_PENDING' THEN 'MFA_PENDING' ELSE NULL END) AS MFA_PENDING
,COUNT (CASE WHEN c.scrape_status = 'ERROR' THEN 'ERROR' ELSE NULL END) AS ERROR
,COUNT (CASE WHEN c.scrape_status ISNULL THEN 'ISNULL' ELSE NULL END) AS "NULL"
,COUNT (CASE WHEN c.scrape_status = '' THEN '' ELSE NULL END) AS "Em BRANCO"
FROM PUBLIC.CONNECTION C,
PUBLIC.INSTITUTION I
WHERE
C.INSTITUTION_ID = I.ID
GROUP BY
EXTRACT (YEAR FROM c.created_at),
EXTRACT (MONTH FROM c.created_at),
I.NAME) as TESTE
order by Ano desc, mes desc
