--- Query indicador e percentual das inst

select *
round((CAST(MFA_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% Error MFA",
round((CAST(CREDENTIAL_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% CREDENTIAL_ERROR",
round((CAST(CONNECTION_OK AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% CONNECTION_OK",
round((CAST(ALREADY_ASSOCIATED AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% ALREADY_ASSOCIATED",
round((CAST(ACCOUNT_NEEDS_ACTION_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% ACCOUNT_NEEDS_ACTION_ERROR",
round((CAST(UNMAPPED_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% UNMAPPED_ERROR",
round((CAST(ACTIVE_SCRAPING_RUNNING AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% ACTIVE_SCRAPING_RUNNING",
round((CAST(ALREADY_LOGGED_IN AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% ALREADY_LOGGED_IN",
round((CAST(TRANSLATE_OK AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% TRANSLATE_OK",
round((CAST(SCRAPE_OK AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% SCRAPE_OK", 
round((CAST(SCRAPE_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% SCRAPE_ERROR",
round((CAST(ACCOUNT_LOCKED_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% ACCOUNT_LOCKED_ERROR",
round((CAST(CONNECTION_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% CONNECTION_ERROR",
round((CAST(CATEGORIZED AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% CATEGORIZED",
round((CAST(CATEGORIZE_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% CATEGORIZE_ERROR",
round((CAST(USER_AUTHORIZATION_NOT_GRANTED AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)),2) as "% USER_AUTHORIZATION_NOT_GRANTED",
round((CAST(UNLOCK_DEVICE AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% UNLOCK_DEVICE",
round((CAST(SELECT_OWNERSHIP AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% SELECT_OWNERSHIP",
round((CAST(MFA_EXPIRED AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% MFA_EXPIRED",
round((CAST(TRANSLATE_ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% TRANSLATE_ERROR",
round((CAST(SITE_NOT_AVAILABLE AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% UNLOCK_DEVICE",
round((CAST(MFA_PENDING AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% SELECT_OWNERSHIP",
round((CAST(ERROR AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% ERROR",
round((CAST("NULL" AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% NULL",
round((CAST("Em BRANCO" AS DECIMAL) * 100) / (CAST(qtd AS DECIMAL)), 2) as "% Em BRANCO"
from (
SELECT EXTRACT (YEAR FROM c.created_at) AS Ano,
EXTRACT (MONTH FROM c.created_at) AS Mes,
I.NAME,
COUNT(I.ID) as QTD,
COUNT (CASE WHEN c.scrape_status = 'MFA_ERROR' THEN 'MFA_ERROR' ELSE NULL END) AS MFA_ERROR,
COUNT (CASE WHEN c.scrape_status = 'CREDENTIAL_ERROR' THEN 'CREDENTIAL_ERROR' ELSE NULL END) AS
CREDENTIAL_ERROR
,COUNT(CASE WHEN c.scrape_status = 'CONNECTION_OK' THEN 'CONNECTION_OK' ELSE NULL END) AS CONNECTION_OK











  
